# Generated by Django 3.2.2 on 2022-03-19 21:47

from django.db import migrations, models
from django.core.management import call_command
from django.db import migrations
from django.core.serializers import base, python

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'data.json', app_label='diseases')


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),

    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RunPython(load_fixture),
    ]
